### PR TITLE
RFC for RFC

### PR DESCRIPTION
**Pull request by rtablada**
[Rendered](https://github.com/rtablada/discussion/blob/rfc/rfc/text/0000-rfc-process.md)

### CODE REVIEW

**Comment by miguelcobain** [comment]
:+1: x 1000

This process did so much good to the Ember and Rust communities that I can't recommend it enough. I hope that it isn't too much of a burden for a smaller community like Adonis.

**Comment by thetutlage** [comment]
@rtablada Thanks a ton 😄 

@miguelcobain Yup I have same worries too, lemme explain my point.

I agree that RFC is the nice way to keep things in track and let all big decisions go via a transparent layer. But also I cannot disregard the fact that Adonis is not as big as Ember and RFC process may stay with me only

## Problem we are trying to solve
The problem we are trying to solve here is, that everyone who is interested in contributing to Adonis knows what's cooking under the table, so they themselves do not re-invent the wheel and for that I will create issues in this repo, for each feature/change I have plans for.

## Why RFC is too early?
Unless we get core contributors and some dedication towards the project, it will be overkilling for me to get RFC in place that everyone respects.

But I will do my best to keep this repo updated with what all I have in pipeline and discuss it with everyone before making the decision.

Hope this helps

**Comment by rtablada** [comment]
> But I will do my best to keep this repo updated with what all I have in pipeline and discuss it with everyone before making the decision.

I think the difference between this and the start of an RFC process would be one or two other community members committing to making sure issues are formatted into the RFC template and then keeping track of the Final Comments Period.

Personally I think that I can help this out each week to help convert issues to RFCs during the transition period, and to help comment on how it might effect my existing projects and how changes would be understood by the Junior engineers I'm training.

---

> The problem we are trying to solve here is, that everyone who is interested in contributing to Adonis knows what's cooking under the table

From a perspective of someone who spends half of my time in Ember and half of my time in Adonis I feel like other contributors like myself come and go and it can be hard to "know what's cooking under the table". While adding issues here for features is a step in the right direction I think it actually may end up being harder to track and understand than the little time in the current process that it would take to format those into the RFC template (which can be modified from the current suggested format).

I think one big key to the RFC as a PR vs an issue is that changes over time can be commented inline and seen.

For instance if there was a hypothetical RFC for Websockets as discussed alot in the Gitter, a first draft of the RFC may have said that it should be inspired or be a thin wrapper around Socket.io with few changes. But, in the comments period @miguelcobain, @thetutlage, and I would have commented that we should take more inspiration from Phoenix channels which may need to go lower level. This change would have been reflected by a commit that could be tracked rather than the issue description changing which would have been untraceable.

**Comment by rtablada** [comment]
I'm traveling currently, but when I get to my computer I will update this PR and the "Motivation" area to mirror that.

**Comment by thetutlage** [comment]
@rtablada 

Thanks for stepping in and showing interest in making RFC a live and continuous process. I will be more than happy to have RFC in place and get the ball rolling to make AdonisJs one of the best frameworks in 2017.

I have created a sample issue of the changes needs to be done for the upcoming major release https://github.com/adonisjs/discussion/issues/19, also a small guidelines to read before contributing to AdonisJs https://github.com/adonisjs/discussion/issues/18.

Lemme know when you have some time to talk about the RFC process in-depth and things required to start implementing it. Again it will be hard for me to keep the process in place alone and I would need support from everyone in the community.

**Comment by rtablada** [comment]
Sorry to go off grid. I had a move last week and then went to hospital and have still been recovering since then.

I will be happy to help with the RFC and discussion process and would be more than happy to further discuss this in-depth and how to start implementing it.

I think I will try during some of my office hours this week to try and get the existing major features in the discussion issues ported to the RFC format with help and I may need help from @thetutlage and @RomainLanz to fill in gaps.

**Comment by thetutlage** [comment]
Get well soon and we are always here formalize a structured process for Adonisjs 👍🏻

**Pull request closed without merging**
